language: objective-c
install: (gem install cocoapods; cd Project;pod install)
xcode_workspace: Project/FormKitDemo.xcworkspace
xcode_scheme: FormKitDemo
xcode_sdk: iphonesimulator
script: xctool -workspace Project/FormKitDemo.xcworkspace -scheme FormKitDemo -sdk iphonesimulator build test -freshInstall -freshSimulator
